### ISSUE TITLE
V1.26 - TR3 rocket launcher + grenade launcher get zero ammo

### ISSUE THREAD

**Issue by StenApp** [JulianOzelRose/TRR-SaveMaster#10]
City of tinnos save 344,

having issues with ammo being zero

version is 1.26

[savegame.dat.txt](https://github.com/JulianOzelRose/TRR-SaveMaster/files/14821491/savegame.dat.txt)

**Comment by JulianOzelRose** [comment]
Thanks for bringing this edge case to my attention... don't know how I missed this for TR3.

[TRR-SaveMaster-Tinnos-Fix.zip](https://github.com/JulianOzelRose/TRR-SaveMaster/files/14827240/TRR-SaveMaster-Tinnos-Fix.zip)

Give that build a try, should work for that case in Lost City of Tinnos. Let me how it works and I will patch the editor accordingly once I test it out on other levels/cases.

**Comment by StenApp** [comment]
This version fixes Tinnos level, testet unlocking of grenade launcher and set grenades and rockets to 20.

Thanks for fixing!
