### ISSUE TITLE
TR3 Harpoon ammo

### ISSUE THREAD

**Issue by Insers** [JulianOzelRose/TRR-SaveMaster#12]
Hello, after editing TR3 savefile everytime my harpoons resets to 0 ingame, on save editor it shows good value, but in game its always 0, and then it dissapears afer level change.

**Comment by JulianOzelRose** [comment]
Hi. Is it writing the ammo incorrectly only when the Harpoon Gun is unequipped? Or does it write incorrectly in both cases?

**Comment by JulianOzelRose** [comment]
Issue is now fixed as of [v1.41](https://github.com/JulianOzelRose/TRR-SaveMaster/releases/tag/v1.41).

**Comment by Insers** [comment]
Thanks :D
