### ISSUE TITLE
TR3 training level save

### ISSUE THREAD

**Issue by MsSepeteus** [JulianOzelRose/TRR-SaveMaster#13]
Hi, is it possible to make a simple solution to save at tr3 training level.

Needed eg. for this: https://www.youtube.com/watch?v=tJ1C_QyVwXQ

Thank you for your great work with excellent editor and extractor.

**Comment by JulianOzelRose** [comment]
Hello,

Give this a try:

[TRR Force Save v0.1.zip](https://github.com/user-attachments/files/17371028/TRR.Force.Save.v0.1.zip)

There's instructions in the README. All you have to do is use the patched `.dll` and you should be able to save on Lara's Home. Just make sure to back up your original `tomb3.dll` before replacing it with the patched version.

When you save on Lara's Home, it will initiate the "New Game" sequence, but it will still save it to the slot you designate -- so it's a minor inconvenience. It may also lead to some whacky behavior when you try to save a game on a "normal" level, but you should still be able to load back from saveable levels. Just swap the original `.dll` back when you want the save function to return back to normal. You can still load the Lara's Home savegame using the original `.dll`.

Let me know how it works.

**Comment by MsSepeteus** [comment]
Thanks , @JulianOzelRose 

Fixed dll works and it's very clean fix only three jumps.
I'll use clean savegame.dat and no need to mix levels, thanks again.
