### ISSUE TITLE
How to use with PS4 game save?

### ISSUE THREAD

**Issue by Th3nicholas** [JulianOzelRose/TRR-SaveMaster#3]
Hello,

Firstly, I sorry if this isn’t the correct place for this question. I having an issue with editing my PS4 game save. 

When I copy my game save off my ps4 there are 2 files sce_sdmemory.bin and a file without an extension but has the same name. So I rename the sce_sdmemory file with no extension to a .dat file and try and use it with save editor it does read it but the information is all wrong and it doesn’t save the information. I’m assuming I need to do something else with the game save I just don’t know what. 

Any help would be greatly appreciated. Thanks.

**Comment by xTheSolutionNOT** [comment]
You need a jailbroken PS4 and Apollos Save tool to decrypt it first. Then you have a memory.dat file, which you can open in the editor. After editing the file, import it back with Apollo to your PS4 save.

**Comment by Th3nicholas** [comment]
That’s unfortunate I don’t have a hacked PS4. I did figured it had something to do with having a hacked save though. Nonetheless, thanks for answering my question.
